### PR TITLE
Add support for setting the start dir via `ElFinder::$path`

### PR DESCRIPTION
**Pull request by hightman**
Now we can specify start directory as following code:
```php
<?= \mihaildev\elfinder\ElFinder::widget([
	'language' => 'zh_CN',
	'controller' => 'backend/elfinder',
	'path' => '@1/subdir',  // HRER!!
	//'filter'           => 'image',
	'callbackFunction' => new \yii\web\JsExpression('function(file, id){console.log(file);}'),
	'containerOptions' => ['style' => 'width:100%;height:610px;']
])
?>
```

### CODE REVIEW

**Comment by hightman** [comment]
Sorry, this may cause confliction with `PathController.php`, but I thinks it is not good idea to change root path via request parameter.

**Comment by hightman** [comment]
It seems elFinder support `roots.$startPath`, see: https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options#startPath

**Comment by MihailDev** [comment]
it's a good idea. but it is necessary to change the name of the parameter may be "startPath"

**Comment by hightman** [comment]
I had tried it, but the effect of `$startPath` is equals to change root path.

That is to say, use `$startPath` will change whole root path, so we can not change to other directories via clicking folder icons.

**Pull request closed without merging**
